### ISSUE TITLE
JS[l|h]int and convention enforcement

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/guides#2]
First question: [jsHint](http://jshint.com/) vs. [jsLint](http://www.jslint.com/)?

I prefer jsHint. I also know the maintainer which seems useful in some sort of useless way.

Here is my current default `.jshintrc` per my [dotfiles](https://github.com/lyzadanger/dotfiles) repo:

``` json

{
    "predef": [
        "define",
        "require",
        "module",
        "process",
        "$"
    ],
    "globalstrict" : true,
    "camelcase"    : true,
    "eqeqeq"       : true,
    "indent"       : 2,
    "nonew"        : true,
    "quotmark"     : "single"
}

```

Some points of thought:
- It likely makes sense to do `.jshintrc`-type enforcement on a project basis (not globally) to allow for differences in client requirements and as to not impose stuff on a user-wide level for people.
- I have active personal leanings with regards to:
  - 2-space tabs. I can live with 4-space but odd numbers are not OK.
  - Single quotes.
  - `camelCase` var names

This `jshintrc` isn't particularly detailed, any other defaults we'd like to see covered? 

Feel free to disagree with anything I have here so far (as long as you're prepared to engage in battle over the few things I highlighted above!). We also need to look at convention enforcement via jscs (or not) and things that are in `.editorconfig`'s universe (FOR THE LOVE OF ALL THAT HAS EVER BEEN SPACES NOT TABS).

Discuss.
/cc @lharding @erikjung

**Comment by spaceninja** [comment]
I'm going to close this, since the team has settled on [eslint](https://github.com/cloudfour/eslint-config)
