### ISSUE TITLE
Create "Modern" CSS Guide

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/guides#23]
I dig a lot about our current CSS guide, but there are a couple of new technologies that can (and should) challenge some of our conventions. We haven't had an opportunity to put this stuff into practice yet, but it's only a matter of time until IE11 is no longer a first-class optimization, freeing us up to pursue the next generation of awesome Cloud Four sites.

I'm including some open questions I have below that I'd love to resolve in a "modern" version of the guide for projects wanting to make the most of what the web has to offer. I'd love for us to discuss these at some point, and please feel free to mention other points to improve or iterate on.

## Where does layout fit in?

Historically, layout in CSS has been pretty much the worst. Flexbox was an improvement, and gave us the ability to make [nicer grid components](https://github.com/suitcss/components-grid). But with CSS Grid so well-supported, it's likely time to move a lot of layout logic from our markup back into stylesheets. (See [this great Rachel Andrew post](https://rachelandrew.co.uk/archives/2017/07/01/you-do-not-need-a-css-grid-based-grid-system/).)

So should these be handled like any component class? Should we be prefixing them like utilities, for example `.l-Mosaic` or `.l-Spread`? Or should we return to the idea of "section" CSS, perhaps only output on specific pages?

## How can we make the most of custom properties?

Similarly well-supported in modern browsers are custom properties. If you haven't seen Lea Verou's talk on this, [you absolutely should](https://www.youtube.com/watch?v=pujRW3lQ5uM).

Put simply, custom properties are a zillion times better when they're handled in-browser. You can do fancier things with inheritance, you can manipulate them via JavaScript, and the resultant CSS will be tinier.

But does this completely negate the need for classic/precompiled/private CSS variables? Should we be going "all-in" and having everything be a property, or should we adopt [an entirely unique syntax](https://github.com/jonathantneal/postcss-advanced-variables) for those? Do we need standards for how we name and organize our properties?

## Can we make animation approaches a first-class citizen of our stylesheets?

This is something I've been thinking about since seeing [Sarah Drasner's talk on Animating Vue](https://www.youtube.com/watch?v=gJDyhmL9O_E), and the power that comes with Vue's rather impressive [animation and transition](https://vuejs.org/v2/guide/transitions.html) capabilities. We need to be pushing animation a bit more in our work, and right now our approach to this is woefully undocumented (and admittedly, not really fleshed out).

**Comment by spaceninja** [comment]
@tylersticka is this still needed, or has the CSS guide since been updated?

**Comment by tylersticka** [comment]
@spaceninja I think the animation portion is the most actionable, but we can probably close this issue.
