### ISSUE TITLE
Branch naming from `feature_all_the_things` to `feature/all-the-things`

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/guides#26]
I'd like to bring forth a proposal that we revise our Git guide to suggest a different naming convention for our Git branches.

Our [Git Guide](https://github.com/cloudfour/guides/tree/master/git) states:

> Prefix the branch name with something meaningful, for example:
>
> - `feature-make_the_thing_better`
> - `bug-the_thing_is_broken`
> - `cleanup-rename_all_the_files`

I wholeheartedly agree with the "prefix the branch name with something meaningful" but would like to propose we change the naming convention to this instead:

- `feature/make-the-thing-better`
- `bug/the-thing-is-broken`
- `cleanup/rename-all-the-files`

This lends itself to a much nicer organization when viewing as directories as well as any Git GUI apps:

![screen shot 2018-07-11 at 11 14 41 am](https://user-images.githubusercontent.com/459757/42591841-b389dba8-84fc-11e8-92a8-a0c49a138f83.png)

Another benefit is it lends itself to [this type of organization](https://docs.microsoft.com/en-us/vsts/git/concepts/git-branching-guidance?view=vsts#name-your-feature-branches-by-convention) as well, when/if needed:

> - `users/username/description`
> - `users/username/workitem`
> - `bugfix/description`
> - `features/feature-name`
> - `features/feature-area/feature-name`
> - `hotfix/description`

I've now been using this naming convention in my current project for a while and really do like how easy it is to organize my branches by directories. I invite you to experience this with me as well. 😃 

@cloudfour/dev @cloudfour/design Thoughts?

**Comment by gerardo-rodriguez** [comment]
Another convention that could be added to this is going from:
```
bug/the-thing-is-broken
```
to
```
bugfix/<issue-number>-<description>
```
As an example: `bugfix/735-sw-not-caching-images`

**Comment by tylersticka** [comment]
@gerardo-rodriguez I agree, as I've often found myself using `fix-*` branch names since it feels weird pushing a branch called "bug." 🐛
