### ISSUE TITLE
Git guide: Who owns merging PRs?

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/guides#29]
Something I realized today might not be represented in our Git guide: When a PR is approved, who merges it?

I always assumed the author is the one who merges, since I consider them the "owner" of the code. But a contractor recently read the guide and got the impression that the reviewer merges the code.

---

/CC @cloudfour/dev

**Comment by gerardo-rodriguez** [comment]
I've seen this question come up before as well. 

> I always assumed the author is the one who merges, since I consider them the "owner" of the code. 

This is the assumption I work under as well. When asked, this is what I respond, FWIW. 😉 

We should make this more clear in the Git Guide. 😬

**Comment by megnotarte** [comment]
I agree! Usual process is author merges. Under rare circumstances, a reviewer will merge.

**Comment by dwolfe** [comment]
I think I read this line:

> If needed, they make small changes right in the branch, test the feature on their machine, commit, and push.

And somehow tacked "and merge" on to the end in my head. I was reading quickly and trying to get through all the guides, so I'll hold my hand up on that. I don't think it's a bad thing to add a sentence specifying that it's the submitter's responsibility to execute the merge, but I don't think it's deficient as is.
