### ISSUE TITLE
JS Guide: return early if condition is not met

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/guides#57]
While [reviewing a PR](https://github.com/cloudfour/lts-patterns/pull/354#pullrequestreview-251808237) @gerardo-rodriguez recommended a pattern he picked up from @Josh68 that we should add to the JS Guide:

> Instead of needing to wrap a larger block of code in an `if` conditional, how about returning from the method if conditions are not met?

```js
start(options) {
  if (!this.element) {
    // Maybe even log a warning, if that makes sense?
    return;
  }

  // If you made it this far, continue on your merry way. :)
  // Also, hello, no extra indentations. ;) 
}
```

> This pattern also helps remove the cognitive load of wondering why many lines later in this block of code why you are indented in so far. 

```
* Scrolls down past `start()` method declaration so it's now offscreen *

"Why have we indented so far again?"

* Scrolls back up losing context of what I was looking at * 

"Oh right, we live in a conditional `if` statement"

* Pauses... *

* Starts scrolling back down *

"Where was I again?"
```
😉

**Comment by calebeby** [comment]
ESLint-plugin-shopify has a rule for this, which we could add to our ESLint config: https://github.com/Shopify/eslint-plugin-shopify/blob/master/docs/rules/prefer-early-return.md

**Comment by spaceninja** [comment]
This was resolved in https://github.com/cloudfour/eslint-config/pull/171
