### ISSUE TITLE
Add editorconfig to code guide wiki

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/guides#6]
We've been talking about enforcing JS/editor conventions on a project-by-project basis (as in, not inflicting draconian requirements globally to everyone). I'm wondering what a good place to stick/manage those defaults would be. Specifically, items like:
- .gitignore
- .jshintrc
- .jscs
- .editorconfig

Any thoughts out there?

**Comment by spaceninja** [comment]
Renaming this ticket since we now have a shared eslint config, and gitignore files need to be different on a per-project basis, but we should still have our standard editorconfig in the wiki.

**Comment by spaceninja** [comment]
Actually, this is done! https://github.com/cloudfour/guides/tree/master/coding
